### ISSUE TITLE
Specify download direction

### ISSUE THREAD

**Issue by ghost** [alcheck/transshift#9]
Hi,

Do you think it would be possible to add an input during the file upload, just to specify in which direction we want the file to be downloaded?

Nonetheless, thanks a lot for your work, it's great to finally have a Transmission Remote for iOS! ;)

**Comment by alcheck** [comment]
Hi,

The download folder is server-side config parameter and can not be changed just for the fact that your app doesn’t have access to the filesystem of bt-server and we have no ability to view the folder structure of bt-server using just rpc protocol.

Отправлено с iPad

**Comment by ghost** [comment]
Hi @alcheck,

From the transmission rpc api it is possible to specify a "download-dir" argument: https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt#L356. 
You're right though by saying that the user would not able to see the folder structure, but it would allow people how know their structure already to move file to specific locations, like a "Movie" folder or a "TV Show" folder (especially useful for apps like Plex or DLNA servers ;) ) 

EDIT: Also you can find apps like https://github.com/YodaDaCoda/chrome-transmission-remote-plus as a javascript example where you can specify this download directory

**Comment by ghost** [comment]
So... I guess it's a no? 😄

**Comment by alcheck** [comment]
Sorry, I have no time for this project for now

**Comment by ghost** [comment]
Okok, no problem, was just curious to have a clear answer! 😉
